#!/usr/bin/env bash
# Writes the licensing configuration compiled into official builds.
#
#   scripts/generate-licensing-config.sh Sources/OpenReaction/Licensing/LicensingConfig.swift
#
# Reads OPENAPPS_DODO_ENV (test|live), OPENAPPS_DODO_PAID_PRODUCT_ID,
# OPENAPPS_DODO_TRIAL_PRODUCT_ID and optional OPENAPPS_BUY_URL,
# OPENAPPS_TRIAL_URL, OPENAPPS_SUPPORT_URL. Product IDs are public
# configuration; there are no secrets here. Fails loudly when anything a
# licensed build needs is missing, so a placeholder can never ship.
set -euo pipefail

out="${1:?output path}"
env_name="${OPENAPPS_DODO_ENV:-}"
paid="${OPENAPPS_DODO_PAID_PRODUCT_ID:-}"
trial="${OPENAPPS_DODO_TRIAL_PRODUCT_ID:-}"
buy_url="${OPENAPPS_BUY_URL:-https://openapps.space/openreaction/#buy}"
trial_url="${OPENAPPS_TRIAL_URL:-https://openapps.space/openreaction/#trial}"
support_url="${OPENAPPS_SUPPORT_URL:-mailto:support@openapps.space}"

case "$env_name" in
    test) host="https://test.dodopayments.com" ;;
    live) host="https://live.dodopayments.com" ;;
    *) echo "error: OPENAPPS_DODO_ENV must be 'test' or 'live' (got '${env_name}')" >&2; exit 1 ;;
esac
for var in OPENAPPS_DODO_PAID_PRODUCT_ID OPENAPPS_DODO_TRIAL_PRODUCT_ID; do
    value="${!var:-}"
    if [[ -z "$value" || "$value" == *PLACEHOLDER* || "$value" == *TODO* ]]; then
        echo "error: $var is missing or a placeholder; create the Dodo products first (LICENSING.md)" >&2
        exit 1
    fi
done

mkdir -p "$(dirname "$out")"
cat > "$out" <<SWIFT
// Generated by scripts/generate-licensing-config.sh. Do not edit or commit.
#if OPENAPPS_LICENSING
import Foundation
import OpenReactionCore

enum LicensingConfig {
    /// Dodo environment: ${env_name}
    static let environment = "${env_name}"
    static let host = URL(string: "${host}")!
    static let products = LicenseProducts(
        paid: ["${paid}"],
        trial: ["${trial}"]
    )
    static let buyURL = URL(string: "${buy_url}")!
    static let trialURL = URL(string: "${trial_url}")!
    static let supportURL = URL(string: "${support_url}")!
}
#endif
SWIFT
echo "==> Wrote ${out} (env ${env_name})"
