#!/usr/bin/env bash
# Writes the licensing configuration compiled into official builds.
#
#   scripts/generate-licensing-config.sh Sources/OpenNotes/Licensing/LicensingConfig.swift
#
# Reads OPENAPPS_DODO_ENV (test|live) and OPENAPPS_DODO_PAID_PRODUCT_ID, plus
# optional OPENAPPS_TRIAL_REGISTRY_BASE_URL, OPENAPPS_BUY_URL and
# OPENAPPS_SUPPORT_URL. There is no trial product: the trial lives in the
# app and registers with the trial registry at
# ${OPENAPPS_TRIAL_REGISTRY_BASE_URL:-https://openapps.space}/api/trial, with
# `env` = OPENAPPS_DODO_ENV. A test build may point the registry at a local
# `wrangler dev` (http://127.0.0.1:8787 or http://localhost:8787). The buy
# button opens the website's OpenNotes page (OPENAPPS_BUY_URL, default
# https://openapps.space/opennotes/), the single place for the price. Product IDs
# are public configuration; there are no secrets here. Fails loudly when
# anything a licensed build needs is missing, so a placeholder can never ship.
set -euo pipefail

out="${1:?output path}"
env_name="${OPENAPPS_DODO_ENV:-}"
paid="${OPENAPPS_DODO_PAID_PRODUCT_ID:-}"
registry_base="${OPENAPPS_TRIAL_REGISTRY_BASE_URL:-https://openapps.space}"
buy_url="${OPENAPPS_BUY_URL:-https://openapps.space/opennotes/}"
support_url="${OPENAPPS_SUPPORT_URL:-}"

case "$env_name" in
    test) host="https://test.dodopayments.com" ;;
    live) host="https://live.dodopayments.com" ;;
    *) echo "error: OPENAPPS_DODO_ENV must be 'test' or 'live' (got '${env_name}')" >&2; exit 1 ;;
esac

# Product IDs: Dodo's `pdt_` form. Placeholder names are refused outright in
# their shouting form and, for a live build, in any casing: the CI checks job
# compiles the test flavour with `pdt_placeholder_…`, and that must never be
# what a release ships.
check_product_id() {
    local var="$1" value="$2" lowered
    lowered="$(printf '%s' "$value" | tr '[:upper:]' '[:lower:]')"
    if [[ ! "$value" =~ ^pdt_[A-Za-z0-9_-]{4,}$ ]] || [[ "$value" == *PLACEHOLDER* || "$value" == *TODO* ]]; then
        echo "error: $var must be a real Dodo product id (pdt_…); create the product first (LICENSING.md)" >&2
        exit 1
    fi
    if [[ "$env_name" == live ]] && [[ "$lowered" == *placeholder* || "$lowered" == *todo* || "$lowered" == *example* || "$lowered" == *dummy* ]]; then
        echo "error: $var is a placeholder ('${value}'); a live build needs the real Dodo product id (LICENSING.md)" >&2
        exit 1
    fi
}
check_product_id OPENAPPS_DODO_PAID_PRODUCT_ID "$paid"

# The registry base: an https origin (no path, query or credentials), or for
# a test build only, a local `wrangler dev` over http. A trailing slash is
# dropped.
registry_base="${registry_base%/}"
https_origin='^https://[A-Za-z0-9.-]+(:[0-9]{1,5})?$'
local_origin='^http://(127\.0\.0\.1|localhost)(:[0-9]{1,5})?$'
if [[ "$registry_base" =~ $https_origin ]]; then
    :
elif [[ "$registry_base" =~ $local_origin ]]; then
    if [[ "$env_name" != test ]]; then
        echo "error: OPENAPPS_TRIAL_REGISTRY_BASE_URL may use a local http registry only in a test build (got '${registry_base}' for ${env_name})" >&2
        exit 1
    fi
else
    echo "error: OPENAPPS_TRIAL_REGISTRY_BASE_URL must be an https:// origin, or http://127.0.0.1[:port] / http://localhost[:port] for a test build (got '${registry_base}')" >&2
    exit 1
fi

# URLs must be https:// or mailto: and contain nothing that could break a
# Swift literal. The support URL is optional; an empty OPENAPPS_BUY_URL
# disables the buy button (it says "coming soon").
swift_optional_url() {
    local value="$1" name="$2"
    if [[ -z "$value" ]]; then echo "nil"; return; fi
    local https_pattern='^https://[A-Za-z0-9._~:/?#@!$&*+,;=%()-]+$'
    local mailto_pattern='^mailto:[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+$'
    if [[ ! "$value" =~ $https_pattern && ! "$value" =~ $mailto_pattern ]]; then
        echo "error: $name must be an https:// or mailto: URL without quotes, spaces or backslashes (got '$value')" >&2
        exit 1
    fi
    echo "URL(string: \"${value}\")"
}
buy_literal="$(swift_optional_url "$buy_url" OPENAPPS_BUY_URL)"
support_literal="$(swift_optional_url "$support_url" OPENAPPS_SUPPORT_URL)"

mkdir -p "$(dirname "$out")"
cat > "$out" <<SWIFT
// Generated by scripts/generate-licensing-config.sh. Do not edit or commit.
#if OPENAPPS_LICENSING
import Foundation
import OpenAppsLicensing

enum LicensingConfig {
    /// Dodo environment, and the trial registry's \`env\`: ${env_name}
    static let environment = "${env_name}"
    static let host = URL(string: "${host}")!
    static let products = LicenseProducts(paid: ["${paid}"])
    static let trialRegistryURL = URL(string: "${registry_base}/api/trial")!
    /// The website's OpenNotes page; nil disables the buy button ("coming soon").
    static let buyURL: URL? = ${buy_literal}
    static let supportURL: URL? = ${support_literal}
}
#endif
SWIFT
echo "==> Wrote ${out} (env ${env_name}, trial registry ${registry_base})"
