import assert from "node:assert/strict";
import { readFile, writeFile } from "node:fs/promises";

const tokens = JSON.parse(
  await readFile(new URL("../design/tokens.json", import.meta.url), "utf8"),
);
const kebab = (name) => name.replaceAll("/", "-");
const declarations = (values, format) =>
  Object.entries(values)
    .map(([name, value]) => `  ${format(name, value)};`)
    .join("\n");
const color = (mode) =>
  declarations(tokens.color[mode], (name, palette) => {
    assert.ok(palette in tokens.palette, `Unknown palette alias: ${palette}`);
    return `--color-${kebab(name)}: var(--palette-${kebab(palette)})`;
  });
assert.deepEqual(Object.keys(tokens.color.light), Object.keys(tokens.color.dark));
assert.equal(
  Object.keys(tokens.palette).length +
    Object.keys(tokens.color.light).length +
    Object.keys(tokens.metrics).length +
    Object.keys(tokens.typography).length,
  89,
);
const css = `/* Generated by scripts/generate-theme.mjs from the Figma token export. */
:root {
${declarations(tokens.palette, (name, value) => `--palette-${kebab(name)}: ${value}`)}
${declarations(tokens.metrics, (name, value) => `--${kebab(name)}: ${name.startsWith("motion/") ? `${value}ms` : `${value / 16}rem`}`)}
${declarations(tokens.typography, (name, value) => (name.startsWith("family/") ? `--font-${name.split("/")[1]}: "${value}"` : `--font-${kebab(name)}: ${name.startsWith("weight/") ? value : `${value / 16}rem`}`))}
}
:root, [data-theme="light"] {
  color-scheme: light;
${color("light")}
}
[data-theme="dark"] {
  color-scheme: dark;
${color("dark")}
}
`;
await writeFile(new URL("../design/tokens.css", import.meta.url), css);
